GET http://localhost:3003/api/blogs
###
GET http://localhost:3003/api/blogs/61e437c448e5ec005e27b123
###
DELETE http://localhost:3003/api/blogs/61e437c448e5ec005e27b123
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Rex Yeniceli - 3",
    "author": "Cem Yeniceli",
    "url": "CemYeniceli.io",
    "likes": 70,
    "userId": "61e6d9ddacfc5782e2e15c06"
}
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "rexyeniceli",
    "name": "Rex Yeniceli",
    "password": "madrex" 
}
###
GET http://localhost:3003/api/users